spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/person?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

#spring:
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/person
#    username: root
#    password: root
#  jpa:
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: true
#    open-in-view: false
#    hibernate:
#      dialect: org.hibernate.dialect.MySQL5Dialect
#      ddl-auto: none